### PR TITLE
Implement resizeHandleComponent

### PR DESCRIPTION
**Pull request by oliv9286**
### Proposed solution

Add resizeHandleComponent as per feature request from https://github.com/bokuweb/react-rnd/issues/532, which already exists in re-resizable which this project depends on

### Testing Done

1. added unit test case
2. added storybook story "customization -> resizeHandleComponent" to see how it's being used

### CODE REVIEW

**Comment by bokuweb** [comment]
@oliv9286 Thanks for your great work :) Looks good :+1:

**Comment by bokuweb** [comment]
@oliv9286 v10.1.0 published :tada:

**Comment by oliv9286** [comment]
thanks for the quick review @bokuweb, first time contributing to open source, feeling like a productive member of the society right now

**Comment by mackosx** [comment]
Good work, thanks!

**Pull request merged**
