### PR TITLE
Fix argument events

### PR DESCRIPTION
**Pull request by bloodmozg**
In FF there was a error that the _Event is not defined_

### CODE REVIEW

**Comment by bokuweb** [comment]
@bloodmozg Thanks!!Sorry.... I was referring to global `event`.... 😭

**Comment by bloodmozg** [comment]
Please, tell me when you update component in npm? :-)

**Comment by bokuweb** [comment]
@bloodmozg published as  @5.0.2

**Comment by bloodmozg** [comment]
Thank you, very much!

**Pull request merged**
