### PR TITLE
add draggableProps

### PR DESCRIPTION
**Pull request by hungdev**
Add draggable props
https://github.com/bokuweb/react-rnd/issues/708

@bokuweb

### CODE REVIEW

**Comment by bokuweb** [comment]
@hungdev Thanks for your request.

Could you please update README.md and add `draggableProps` to `interface Props {...}`

**Comment by bokuweb** [comment]
@hungdev Thanks. Which props do you want to give them, by the way?

**Comment by hungdev** [comment]
its draggableProps, if we have draggableProps, so we can pass any of props react-draggable through draggableProps
for example: if we want pass props `allowAnyClick: true`, we cant pass it through `draggableProps`

**Comment by bokuweb** [comment]
@hungdev Thanks :) Do you have any other `props` you'd like to add? If not, I think we should add `allowAnyClick` to rnd's props.

**Comment by chrisstiles** [comment]
Is there a chance this might get merged soon? Right now when using React in strict mode it logs a warning about `ReactDOM.findDOMNode()` being deprecated. React Draggable allows you to pass a `nodeRef` prop to avoid this, so it would be great if we could pass that prop through `draggableProps`. Thanks for the great work!

**Comment by bokuweb** [comment]
https://github.com/bokuweb/react-rnd/pull/715/files

@hungdev @chrisstiles Thanks
I added `al;owAnyClick` and `nodeRef`. Please try latest version.

**Comment by chrisstiles** [comment]
@bokuweb That was fast, thank you for adding `nodeRef`! I'm able to see the prop, but I'm seeing a couple issues when I try passing a ref to it. 

I'm using Typescript, and it is throwing the following error. 

```
Type 'RefObject<HTMLDivElement>' is not assignable to type '((instance: typeof Component | null) => void) | RefObject<typeof Component> | null | undefined'.
```

I think this should be a pretty simple fix. React-Draggable types `nodeRef` as `React.RefObject<HTMLElement>`. The React-Draggable docs actually show the type as matching what has been added to react-rnd, but the actual type in their `index.d.ts` file is different.

https://github.com/STRML/react-draggable/blob/master/typings/index.d.ts
```Typescript
export interface DraggableCoreProps {
  ...
  nodeRef?: React.RefObject<HTMLElement>,
  ...
}
```


https://github.com/bokuweb/react-rnd/blob/master/src/index.tsx
```Typescript
export interface Props {
  ...
  nodeRef?: React.Ref<typeof React.Component>;
  ...
}
```

Once I change that typing the error goes away. However, dragging becomes super jittery. The ref I'm using is a `<div>` element that is the first child of the `<Rnd />` component (which is how the React-Draggable docs show it being added). I haven't investigated this much, but it looks to me like the position is being updated multiple times on each drag event.

rnd

**Workaround:**
A workaround I found would be to wrap the `<Rnd />` component in a parent `<div>`, and use that element as the ref, but that doesn't seem like the correct solution.


```jsx
<div ref={ref}>
  <Rnd
    nodeRef={ref}
    default={{
      x: 0,
      y: 0,
      width: 200,
      height: 100
    }}
  >
    <div>Content Here</div>
  </Rnd>
</div>
``` 

Thanks again for your work. Let me know if you'd like me to investigate this further.

**Comment by bokuweb** [comment]
@chrisstiles Ooops, if you are ok, could you please create pull request about `nodeRef` ?

**Comment by chrisstiles** [comment]
@bokuweb Sure, I'll give it a shot 👍

**Comment by chrisstiles** [comment]
@bokuweb I had a chance to look into this, and the janky dragging appears to be happening because React-Draggable is expecting the `nodeRef` parameter to reference its top level child node. However, re-resizable adds its own child div and then renders react-rnd's children inside of that. Therefor the `nodeRef` parameter would actually be referencing a descendent child.

The issue can be fixed by manually passing in the resizable ref like this:

```jsx
<Draggable
  ...
  nodeRef={{ current: this.getSelfElement() }}
>
  <Resizable
    ...
  >
    {children}
  </Resizable>
</Draggable>
```

It seems a little weird manually creating the ref object, but it is working fine in all the storybooks. If this is fine with you I can create a PR with this change and remove the `nodeRef` parameter from documentation in `README.md`.

**Pull request closed without merging**
